## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [18]:
import numpy as np

In [19]:
n = 11
result = list(np.arange(0, n))
result.reverse()

result

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [20]:
np.array(result)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [21]:
a = np.diag(np.arange(1, 20, 4), k=0)
print(a)

[[ 1  0  0  0  0]
 [ 0  5  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 13  0]
 [ 0  0  0  0 17]]


In [22]:
np.trace(a)

45

## Задание 3
Решите систему уравнений:
* 4x + 2y + z = 4
* x + 3y = 12
* 5y + 4z = -3

In [23]:
# коэффициенты при переменных в левой части уравнения

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [24]:
# значения в правой части уравнения

b = np.array( [4, 12, -3] )

In [25]:
# решение

from numpy import linalg

In [26]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [27]:
# проверка верности

np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

## Задание 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

Матрица в виде numpy array:

In [28]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [29]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [30]:
def cosine(users_stats, next_user_stats):
    """
    Подсчет косинусного сходства между очередным пользователем и всеми пользователями из массива user_stats
    """
    bLength = np.linalg.norm(next_user_stats) # посчитаем длину вектора next_user_stats
    # посчитаем длины векторов users_stats
    for i in range(0, len(users_stats)):
        aLength = np.linalg.norm(users_stats[i,])
        return np.dot(users_stats, next_user_stats) / (aLength * bLength)

In [31]:
for i in users_stats:
    cos = cosine(users_stats[i,], next_user_stats)
    print(cos)

[0.4 1.  0.2 0.2 0.2 0.2]
[0.84515425 0.84515425 0.3380617  0.84515425 0.16903085 0.16903085]
[0.4 0.2 1.  0.2 0.2 0.2]
[0.84515425 0.84515425 0.3380617  0.84515425 0.16903085 0.84515425]
[0.2 0.2 1.  0.4 0.2 0.2]
[0.2 0.2 0.2 0.2 0.2 0. ]
[0.84515425 0.16903085 0.16903085 0.16903085 0.16903085 0.16903085]
[0.2 1.  1.  0.2 0.2 0.2]
[0.2 0.2 0.2 1.  1.  1. ]
[0.84515425 0.16903085 0.16903085 0.3380617  0.84515425 0.3380617 ]
